version: "3.5"

services:
  db:
    image: 'postgis/postgis:12-master'
    volumes:
      - ${PWD-.}/docker/data/postgres:/var/lib/postgresql/data
      - ./docker.postgres.init.sql:/docker-entrypoint-initdb.d/docker.postgres.init.sql
    environment:
      POSTGRES_HOST: db
      PGDATA: /tmp
    env_file: .env
    ports:
      - '5432:5432'